In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import datetime
%load_ext autoreload
%autoreload 2


## Load the training data into feature matrix, class labels, and event ids:

In [2]:
%run proj1_helpers.py
DATA_TRAIN_PATH = 'train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [3]:
print(y)
print('----------------------------------')
print(tX)
print('----------------------------------')
print(ids)

[ 1. -1. -1. ...  1. -1. -1.]
----------------------------------
[[ 138.47    51.655   97.827 ...    1.24    -2.475  113.497]
 [ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 ...
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]
 [  94.951   19.362   68.812 ... -999.    -999.       0.   ]
 [-999.      72.756   70.831 ... -999.    -999.       0.   ]]
----------------------------------
[100000 100001 100002 ... 349997 349998 349999]


In [4]:
tx = np.insert(tX, 0, 1, axis=1)

In [5]:
tx

array([[   1.   ,  138.47 ,   51.655, ...,    1.24 ,   -2.475,  113.497],
       [   1.   ,  160.937,   68.768, ..., -999.   , -999.   ,   46.226],
       [   1.   , -999.   ,  162.172, ..., -999.   , -999.   ,   44.251],
       ...,
       [   1.   ,  105.457,   60.526, ..., -999.   , -999.   ,   41.992],
       [   1.   ,   94.951,   19.362, ..., -999.   , -999.   ,    0.   ],
       [   1.   , -999.   ,   72.756, ..., -999.   , -999.   ,    0.   ]])

## Cleaning the data
There seems to be quiet a few incorrect values "-999", for now we'll set these equal to the average of their respective column.

In [6]:
tx = np.where(tx==-999, np.nan, tx) # replace -999 value with nan
col_mean = np.nanmean(tx, axis=0)
inds_nan = np.where(np.isnan(tx))
tx[inds_nan] = np.take(col_mean, inds_nan[1])

In [7]:
np.round(tx,1)

array([[  1. , 138.5,  51.7, ...,   1.2,  -2.5, 113.5],
       [  1. , 160.9,  68.8, ...,  -0. ,  -0. ,  46.2],
       [  1. , 121.9, 162.2, ...,  -0. ,  -0. ,  44.3],
       ...,
       [  1. , 105.5,  60.5, ...,  -0. ,  -0. ,  42. ],
       [  1. ,  95. ,  19.4, ...,  -0. ,  -0. ,   0. ],
       [  1. , 121.9,  72.8, ...,  -0. ,  -0. ,   0. ]])

Changing predictions {-1;1} --> {0;1}

In [8]:
y_log = np.copy(y)
y_log = np.where(y_log==-1, 0, y_log)

In [9]:
y_log

array([1., 0., 0., ..., 1., 0., 0.])

Getting the min and max values for each columns of tx

In [10]:
from implementations import *
minmax = dataset_minmax(tx)

In [11]:
minmax

[[1.0, 1.0],
 [9.044, 1192.026],
 [0.0, 690.075],
 [6.329, 1349.351],
 [0.0, 2834.999],
 [0.0, 8.503],
 [13.602, 4974.979],
 [-18.066, 16.69],
 [0.208, 5.684],
 [0.0, 2834.999],
 [46.104, 1852.462],
 [0.047, 19.773],
 [-1.414, 1.414],
 [0.0, 1.0],
 [20.0, 764.408],
 [-2.499, 2.497],
 [-3.142, 3.142],
 [26.0, 560.271],
 [-2.505, 2.503],
 [-3.142, 3.142],
 [0.109, 2842.617],
 [-3.142, 3.142],
 [13.678, 2003.976],
 [0.0, 3.0],
 [30.0, 1120.573],
 [-4.499, 4.499],
 [-3.142, 3.141],
 [30.0, 721.456],
 [-4.5, 4.5],
 [-3.142, 3.142],
 [0.0, 1633.433]]

Normalized dataset

In [28]:
tx_normalized = np.copy(tx)
normalize_dataset(tx_normalized, minmax)

In [13]:
print(tx_normalized)

[[1.         0.10940657 0.07485418 ... 0.63777778 0.10614258 0.06948372]
 [1.         0.1283984  0.09965294 ... 0.49868386 0.4997482  0.02829991]
 [1.         0.09536454 0.23500634 ... 0.49868386 0.4997482  0.0270908 ]
 ...
 [1.         0.08149997 0.08770931 ... 0.49868386 0.4997482  0.02570782]
 [1.         0.07261903 0.02805782 ... 0.49868386 0.4997482  0.        ]
 [1.         0.09536454 0.10543202 ... 0.49868386 0.4997482  0.        ]]


Standardized dataset (works well if features are distributed according to a gaussian curve)

In [14]:
tx_standardized = np.copy(tx)
means = column_means(tx_standardized)
stdevs = column_stdevs(tx_standardized, means)
standardize_dataset(tx_standardized, means, stdevs)

In [15]:
print(tx_standardized)

[[ 1.00000000e+00  3.14910026e-01  6.83318303e-02 ...  1.14381645e+00
  -2.52713783e+00  4.12509672e-01]
 [ 1.00000000e+00  7.40825545e-01  5.52503718e-01 ...  2.27720450e-14
  -9.07313667e-15 -2.73819417e-01]
 [ 1.00000000e+00 -1.00190088e-12  3.19514914e+00 ...  2.27720450e-14
  -9.07313667e-15 -2.93969258e-01]
 ...
 [ 1.00000000e+00 -3.10930051e-01  3.19315808e-01 ...  2.27720450e-14
  -9.07313667e-15 -3.17016595e-01]
 [ 1.00000000e+00 -5.10096314e-01 -8.45322280e-01 ...  2.27720450e-14
  -9.07313667e-15 -7.45437922e-01]
 [ 1.00000000e+00 -1.00190088e-12  6.65334753e-01 ...  2.27720450e-14
  -9.07313667e-15 -7.45437922e-01]]


## Splitting the data into train and test datasets

In [16]:
ratio = 0.8 # 100ratio% of the data will be used to train the model

In [17]:
x_train, y_train, x_test, y_test = split_data(tx, y, ratio, seed=1)

In [18]:
x_train_log, y_train_log, x_test_log, y_test_log = split_data(tx, y_log, ratio, seed=1)

In [19]:
x_train_log_norm, y_train_log_norm, x_test_log_norm, y_test_log_norm = split_data(tx_normalized, y_log, ratio, seed=1)

In [20]:
x_train_log_stand, y_train_log_stand, x_test_log_stand, y_test_log_stand = split_data(tx_standardized, y_log, ratio, seed=1)

## Testing the functions

In [29]:
weights_LS = least_squares(y_train, x_train)[1]
cat_accuracy_train, f1_score_train = metrics(weights_LS,y_train,x_train)
cat_accuracy_test, f1_score_test = metrics(weights_LS,y_test,x_test)


print("Categorical accuracy train : ",cat_accuracy_train," || f1_score train: ",f1_score_train)
print("Categorical accuracy test : ",cat_accuracy_test," || f1_score test: ",f1_score_test)

Categorical accuracy train :  0.74526  || f1_score train:  0.29218932789111
Categorical accuracy test :  0.7438212040092137  || f1_score test:  0.2880090136041475


In [30]:
weights_LSGD1 = least_squares_GD(y_train, x_train, np.zeros(31), 100, 0.000001)[1]
cat_accuracy_train, f1_score_train = metrics(weights_LSGD1,y_train,x_train)
cat_accuracy_test, f1_score_test = metrics(weights_LSGD1,y_test,x_test)


print("Categorical accuracy train : ",cat_accuracy_train," || f1_score train: ",f1_score_train)
print("Categorical accuracy test : ",cat_accuracy_test," || f1_score test: ",f1_score_test)

# THIS CONVERGES INTO A LOCAL MINIMUM, solution: Dynamic Step Size ?

Categorical accuracy train :  0.66599  || f1_score train:  0.02449624654286843
Categorical accuracy test :  0.6669453313293193  || f1_score test:  0.023779812643900382


In [31]:
weights_LSGD2 = least_squares_GD(y, tx, [-1.15430619e+00,  1.82637143e-04, -7.20672107e-03, -6.45384640e-03,
        -1.73123839e-05,  2.32665195e-02,  4.20381986e-04,  2.50304362e-03,
         3.60203545e-01, -1.26385429e-03, -2.84568774e+00, -2.22719927e-01,
         9.89163555e-02,  3.56752661e-01,  2.85396180e+00, -6.42020723e-04,
        -4.57219107e-04,  2.85879539e+00, -6.80776737e-04,  1.38605239e-03,
         3.15125355e-03,  5.15272243e-04, -3.71558734e-04,  4.27220740e-02,
        -1.01225645e-03,  4.70620275e-04,  1.34341503e-04, -2.12423006e-03,
         1.42389540e-03, -1.78105047e-03,  2.84577828e+00], 100, 0.000001)[1]

cat_accuracy_train, f1_score_train = metrics(weights_LSGD2,y_train,x_train)
cat_accuracy_test, f1_score_test = metrics(weights_LSGD2,y_test,x_test)


print("Categorical accuracy train : ",cat_accuracy_train," || f1_score train: ",f1_score_train)
print("Categorical accuracy test : ",cat_accuracy_test," || f1_score test: ",f1_score_test)

# IT STAYS IN THE ABSOLUTE MINIMUM WHEN USING THAT AS A STARTING POINT

Categorical accuracy train :  0.74516  || f1_score train:  0.2916860631478247
Categorical accuracy test :  0.7437055878193898  || f1_score test:  0.28759185227489054


In [33]:
weights_LSSGD = least_squares_SGD(y, tx, np.zeros(31), 10, 0.000001)[1]

cat_accuracy_train, f1_score_train = metrics(weights_LSSGD,y_train,x_train)
cat_accuracy_test, f1_score_test = metrics(weights_LSSGD,y_test,x_test)


print("Categorical accuracy train : ",cat_accuracy_train," || f1_score train: ",f1_score_train)
print("Categorical accuracy test : ",cat_accuracy_test," || f1_score train: ",f1_score_test)

Categorical accuracy train :  0.70589  || f1_score train:  0.345651337747687
Categorical accuracy test :  0.7052498643733158  || f1_score train:  0.3426659493400349


In [25]:
lambda_ = 0.005

weights_RR = ridge_regression(y_train, x_train, lambda_)[1]
cat_acc_test, f1_score_test = metrics(weights_RR, y_test, x_test)

print(cat_acc_test, f1_score_test)

0.7438212040092137 0.2880090136041475


In [27]:
num_iterations = 10000
lr = 0.005
w = np.zeros(31)
%run implementations.py
weights_log_reg = logistic_regression(x_train_log, y_train_log, w, lr, num_iterations)

TypeError: logistic_regression() missing 2 required positional arguments: 'lr' and 'num_iterations'

In [26]:
num_iterations = 100000
lr = 0.005
w = np.zeros(31)
%run implementations.py
weights_log_reg = logistic_regression(x_train_log_stand, y_train, x_test_log_stand, y_test, w, lr, num_iterations)

NameError: name 'sigmoid_activation' is not defined

## Generate predictions and save ouput in csv format for submission:

In [21]:
DATA_TEST_PATH = 'test.csv'
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [18]:
tX_test = np.insert(tX_test, 0, 1, axis=1)

NameError: name 'tX_test' is not defined

In [42]:
time_day = datetime.datetime.now().day
time_hour = datetime.datetime.now().hour
time_min = datetime.datetime.now().minute
time_second = datetime.datetime.now().second

time = str(time_day)+"-"+str(time_hour)+"-"+str(time_min)+"-"+str(time_second)

OUTPUT_PATH = 'submission'+"_"+str(time)+".csv"
print(weights_LS.shape)
y_pred = predict_labels(weights_LS, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

(30,)
